# Generated by Django 2.1.5 on 2020-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
        migrations.AddField(
            model_name='cliente',
            name='credit_card',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='names',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_name',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
