# Generated by Django 2.1.5 on 2020-08-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20200812_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='names',
        ),
    ]
