# Generated by Django 2.1.5 on 2020-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField(max_length=80)),
                ('foto', models.TextField(max_length=80)),
            ],
        ),
    ]
