# Generated by Django 2.1.5 on 2020-08-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_remove_vendedor_productos'),
        ('productos', '0003_auto_20200810_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Vendedor'),
            preserve_default=False,
        ),
    ]
