# Generated by Django 2.1.5 on 2020-08-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20200813_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(max_length=100),
        ),
    ]
