# Generated by Django 2.1.5 on 2020-08-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20200810_0120'),
        ('vendedor', '0002_auto_20200810_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
    ]
