# Generated by Django 2.1.5 on 2020-08-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_vendedor_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='productos',
        ),
    ]
